spring.application.name=visitor
spring.profiles.active=local
server.port=8081

###########################         DATABASE
spring.jpa.show-sql=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

###########################         DISABLE AUTOMATIC CONVERSION TO SNAKE_CASE
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

###########################         LOGGING
logging.level.root=ERROR
logging.level.com.manage=INFO
logging.level.org.springframework.boot.web.embedded.tomcat=INFO

############################         SWAGGER
springdoc.swagger-ui.doc-expansion=none

###########################         SECURITY
jwt.secret-key=0c99843ebfde7b4fc47ef6eb2fnQ3g$rR#RM*t7bZNUr!d%X2xD8$E2Xcba910b2a104402f78106720f4ff12e9afd938
jwt.expiration-time=180000000

###########################         FLYWAY
spring.flyway.url =jdbc:mysql://localhost:3307/visitor
spring.flyway.user=migrationAdmin
spring.flyway.password=migration@26