ALTER TABLE employee
    ADD sexe VARCHAR(255) NULL;

ALTER TABLE role_feature
    ADD CONSTRAINT FK_ROLE_FEATURE_ON_FEATUREID FOREIGN KEY (feature_id) REFERENCES feature (id);

ALTER TABLE role_feature
    ADD CONSTRAINT FK_ROLE_FEATURE_ON_ROLEID FOREIGN KEY (role_id) REFERENCES `role` (id);

ALTER TABLE role_worker
    ADD CONSTRAINT FK_ROLE_WORKER_ON_ROLEID FOREIGN KEY (role_id) REFERENCES `role` (id);

ALTER TABLE role_worker
    ADD CONSTRAINT FK_ROLE_WORKER_ON_WORKERID FOREIGN KEY (worker_id) REFERENCES worker (id);

ALTER TABLE worker
    ADD CONSTRAINT FK_WORKER_ON_JOBID FOREIGN KEY (job_id) REFERENCES job (id);

ALTER TABLE worker_visitor
    ADD CONSTRAINT FK_WORKER_VISITOR_ON_VISITORID FOREIGN KEY (visitor_id) REFERENCES visitor (id);

ALTER TABLE worker_visitor
    ADD CONSTRAINT FK_WORKER_VISITOR_ON_WORKERID FOREIGN KEY (worker_id) REFERENCES worker (id);